# Generated by Django 5.0.4 on 2025-01-20 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0002_alter_tutor_model_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor_model',
            name='transcript',
            field=models.ImageField(upload_to='profile_image'),
        ),
        migrations.AlterField(
            model_name='tutor_model',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_m', to=settings.AUTH_USER_MODEL),
        ),
    ]
