# Generated by Django 5.0.4 on 2025-03-06 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0005_alter_tutor_model_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutor_model',
            old_name='transcript',
            new_name='profile',
        ),
    ]
