# Generated by Django 5.0.4 on 2025-03-06 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0006_rename_transcript_tutor_model_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor_model',
            name='expertise',
            field=models.CharField(max_length=64),
        ),
    ]
