# Generated by Django 5.0.4 on 2025-03-16 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0007_alter_tutor_model_expertise'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor_model',
            name='price_per_hour',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tutor_model',
            name='unit',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
