# Generated by Django 5.0.4 on 2025-03-16 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0008_tutor_model_price_per_hour_tutor_model_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor_model',
            name='transcript',
            field=models.ImageField(default=1, upload_to='transcript'),
            preserve_default=False,
        ),
    ]
